---
#- name: Add .my.cnf
#  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0622

- name: Set root Password
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} state=present
  with_items:
    - "127.0.0.1"
    - localhost

- name: Add .my.cnf
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0644

- name: Reload privilege tables
#  command: mysql -u root -p{{ mysql_root_password }} -e "{{ item }}"
  command: 'mysql -e "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: Remove anonymous users
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User=''
  changed_when: False

- name: Disallow root login remotely
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: Restarting mysql
  service: name=mysql state=restarted
  when: ansible_os_family == "Debian"


#- name: Restarting mysql
#  service: name=mariadb state=restarted
#  when:
#    - ansible_os_family == "RedHat"
#    - ansible_distribution_major_version == "7"

#- name: Restarting mysql
#  service: name=mysqld state=restarted
#  when:
#    - ansible_os_family == "RedHat"
#    - ansible_distribution_major_version == "6"
#  when: ansible_os_family == "RedHat"
