---
- name: Start database
  service: name=mysqld state=started

- name: Restart database
  service: name=mysqld state=restarted

- name: Restart apache
  service: name=httpd state=restarted

- name: zabbix-server restart
  service: name=zabbix-server state=restarted

- name: zabbix-agent restart
  service: name=zabbix-agent state=started
