---
#- name: Start mysql
#  service: name=mysql state=started

#- name: Retart mysql
#  service: name=mysql state=restarted

#- name: Start mysqld
#  service: name=mysqld state=started

#- name: Restart mysqld
#  service: name=mysqld state=restarted

- name: Restart httpd
  service: name=httpd state=restarted
  
- name: Start httpd
  service: name=httpd state=started
  
- name: Restart apache
  service: name=apache2 state=restarted
  
- name: Start apache
  service: name=apache2 state=started
  
- name: zabbix-server restart
  service: name=zabbix-server state=restarted

- name: zabbix-agent restart
  service: name=zabbix-agent state=started
